clc;
clear;

clear serialport;
imaqreset;

%% =========================================================
%% Camera settings
%% =========================================================

gain = 0;

%% =========================================================
%% Arduino + NeoPixel
%% =========================================================

a = arduino('COM6','Mega2560','Libraries','Adafruit/NeoPixel');

%% Brightfield / reflection LEDs (D7)

nstrip_bf = addon( ...
    a,...
    'Adafruit/NeoPixel',...
    'D7',...
    16,...
    'NeoPixelType','GRB');

%% Darkfield LEDs (D10)

nstrip_df = addon( ...
    a,...
    'Adafruit/NeoPixel',...
    'D10',...
    25,...
    'NeoPixelType','GRB');

%% =========================================================
%% LED geometry
%% =========================================================

M_led = 0.6;

ylocation = [-8.455, -6.839, -2.61, 2.615, 6.842, 8.455, 6.839,...
    2.61, -2.615, -6.842, -4.059, -4.069, 1.589, 5.002, 1.575, 0] ...
    * M_led * 1e-3;

xlocation = [-0.003, -4.972, -8.042, -8.04, -4.967, 0.003, 4.972,...
    8.042, 8.04, 4.967, 2.924, -2.91, -4.743, 0.007, 4.748, 0] ...
    * M_led * 1e-3;

%% =========================================================
%% Reflection rings (D7)
%% =========================================================

ring0 = {'16'};
ring1 = {'15','14','13','12','11'};
ring2 = {'10','9','8','7','6','5','4','3','2','1'};

rings_bf = {ring0, ring1, ring2};

%% =========================================================
%% Darkfield rings (D10)
%% =========================================================

ring_df0 = {'10','9','8','7','6','5','4','3','2','1'};

ring_df1 = { ...
    '25','24','23','22','21',...
    '20','19','18','17','16',...
    '15','14','13','12','11'};


rings_df = {ring_df0, ring_df1};

%% =========================================================
%% HDR exposure banks
%% =========================================================

% ---------- MIN ----------
exp_bf_min = [500000 700000 1000000];
exp_df_min = [1200000 1500000];

% ---------- MID ----------
exp_bf_mid = [1000000 1300000 1600000];
exp_df_mid = [1800000 2200000];

% ---------- MAX ----------
exp_bf_max = [1800000 2200000 2600000];
exp_df_max = [3000000 3500000];

%% =========================================================
%% Save directory
%% =========================================================

thisDir = pwd;

rootDir = fullfile(thisDir,'capture','Capture');

if ~exist(rootDir,'dir')
    mkdir(rootDir);
end

ts = datestr(now,'yyyymmdd_HHMMSS');

saveRoot = fullfile(rootDir,['capture_' ts]);

mkdir(saveRoot);

fprintf('All data saved to:\n%s\n\n',saveRoot);

%% =========================================================
%% HDR acquisition
%% =========================================================

%% ---------- MIN ----------

cap_min = capture_scan_reflection( ...
    nstrip_bf,...
    nstrip_df,...
    rings_bf,...
    rings_df,...
    exp_bf_min,...
    exp_df_min,...
    gain,...
    struct( ...
        'save_root',saveRoot,...
        'save_tag','HDR_MIN',...
        'brightness',0.6,...
        'avgPerLED',1));

%% ---------- MID ----------

cap_mid = capture_scan_reflection( ...
    nstrip_bf,...
    nstrip_df,...
    rings_bf,...
    rings_df,...
    exp_bf_mid,...
    exp_df_mid,...
    gain,...
    struct( ...
        'save_root',saveRoot,...
        'save_tag','HDR_MID',...
        'brightness',0.6,...
        'avgPerLED',1));

%% ---------- MAX ----------

cap_max = capture_scan_reflection( ...
    nstrip_bf,...
    nstrip_df,...
    rings_bf,...
    rings_df,...
    exp_bf_max,...
    exp_df_max,...
    gain,...
    struct( ...
        'save_root',saveRoot,...
        'save_tag','HDR_MAX',...
        'brightness',0.6,...
        'avgPerLED',1));

%% =========================================================
%% Turn everything OFF
%% =========================================================

for n = 1:16
    writeColor(nstrip_bf,n,[0 0 0]);
end

for n = 1:25
    writeColor(nstrip_df,n,[0 0 0]);
end

fprintf('\nHDR acquisition completed.\n');